
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: air ./src/main.go -b 0.0.0.0
    depends_on:
      - db 
      - kafka
    networks:
      - internal  

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
     - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - internal
  
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - .:/usr/src/app  
    command: air ./src/main.go -b 0.0.0.0
    depends_on:
      - core
    networks:
      - internal

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - internal   

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - internal  

networks:
  internal:

volumes:
  postgres-db: