
services:
  core:
    build:
      context: .
      dockerfile: ./shoplifter-core/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0