FROM golang:1.24.2

WORKDIR /usr/src/app

RUN go install github.com/air-verse/air@latest

COPY .env .
COPY shoplifter-gateway ./shoplifter-gateway


WORKDIR  /usr/src/app/shoplifter-gateway

RUN go mod tidy

RUN go build -o ./tmp/main ./src/main.go
